### ISSUE TITLE
Menu fonts too thin / difficult to read

### ISSUE THREAD

**Issue by Gorobei** [conema/monterail-fulldark#63] opened 2021-02-01 11:02 UTC
Hi.

I like the fulldark theme a lot, except for the menus and context-menu fonts, which are very thin and difficult to read. How and where (in which css file) can I change them to regular fonts (Arial/Verdana). Another way of fixing them would be to be shown as white fonts on dark-gray background (like in the pull-down menu for the identities list from the new message window).
![MenuFonts](https://user-images.githubusercontent.com/78352816/106448482-1faf2f00-6483-11eb-88fc-354d95e22252.png) ![ContxtMenuFonts](https://user-images.githubusercontent.com/78352816/106448508-2b025a80-6483-11eb-8c3a-e16a60320c89.png)

Another problem is that in the Calendar tab, the type of Events pull-down menu is completely white and only shows the text when moving the cursor up and down:
![CalendarEvents](https://user-images.githubusercontent.com/78352816/106449524-59346a00-6484-11eb-9869-991249191e3d.png)

As well another small problem it is the selection color of the icons from the filtering bar:
![FilterBarIcons](https://user-images.githubusercontent.com/78352816/106448522-305fa500-6483-11eb-88ec-ea9be506a938.png)

**Comment by conema** [comment] 2021-02-01 14:54
Hi @Gorobei,
I can't reproduce your issues. Could you give me:
-  monterail theme version
- thunderbird theme (light, dark or default)
- OS and OS version
- OS theme (light or dark)

Here how it should appear:
![immagine](https://user-images.githubusercontent.com/12801153/106474592-58f89680-64a5-11eb-9a9c-f85d87555746.png)
![immagine](https://user-images.githubusercontent.com/12801153/106474475-3f574f00-64a5-11eb-8f62-50da780cc90f.png)
![immagine](https://user-images.githubusercontent.com/12801153/106474516-4aaa7a80-64a5-11eb-9275-320836dec231.png)

**Comment by Gorobei** [comment] 2021-02-02 08:53
Hi.

* monterail theme version: **3.2.1** (using TB 78.7.0)
* thunderbird theme (light, dark or default): **default**
* OS and OS version: **Windows 7 SP1 64bit**
* OS theme (light or dark): **Default** (unaltered)

Well, I'm sure that on Apple the theme is looking better, but, unfortunately, Windows is worse at font rendering. Anyhow, how can I change the fonts for the menus to the default SegoeUI/Arial/Verdana and the background to dark-gray/black?

As for the calendar I thing you are showing me the Today pane whereas I was referring to the Event type pull-down menu from the (full) calendar tab.

**Comment by conema** [comment] 2021-02-02 11:38
> I'm sure that on Apple the theme is looking better, unfortunately, Windows is worse at font rendering

The strange thing is that I'm using Windows too (windows 10)

> how can I change the fonts for the menus to the default SegoeUI/Arial/Verdana 

Try to add this:
```
.menu-text, .menu-iconic-text {
    font-family: 'Arial' !important;
}
```
In line #95 of the root.css file https://github.com/conema/monterail-fulldark/blob/d83513f64fbcaa2c45c27c1806a80a8ffdc39cc6/content/skin/root.css#L91-L101

Change Arial with your prefered font.

> As for the calendar I thing you are showing me the Today pane whereas I was referring to the Event type pull-down menu from the (full) calendar tab.

You are right, found it, now it's fixed:
![immagine](https://user-images.githubusercontent.com/12801153/106594472-6e77ca00-6552-11eb-96c9-a5eeb6353052.png)


This new version should resolve your last two isseus (bg to pull-down, bg color of selected icons on filtering bar). Could you try it and let me now if it works?

[monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5910811/monterail-fulldark.zip)

**Comment by Gorobei** [comment] 2021-02-03 09:36
Thank you. 
Indeed, the Calendar Event menu is fixed now and, after changing the root.css, the menu fonts were replaced with Arial.  Anyhow, would it be possible, by changing the root.css, to make the menus look like the pull-down menu from the Events - white fonts on dark-gray background? This will look better and will give a more consistent look to the theme.

**Comment by conema** [comment] 2021-02-03 10:43
Are you talking about the menu bar? 

![immagine](https://user-images.githubusercontent.com/12801153/106733851-a9d9cd80-6612-11eb-830a-266e360b39bc.png)

**Comment by Gorobei** [comment] 2021-02-03 10:48
Yes, I'm talking about all the menu bars (from the main window or from the compose message window) and the right-click context menu.

**Comment by conema** [comment] 2021-02-03 14:29
Now the menus should be more consistent. Could you double check it? 

[monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5919081/monterail-fulldark.zip)

**Comment by Gorobei** [comment] 2021-02-03 16:08
Ok. You are on the good path.
Firstly, the separation lines between menu categories are too thick & white. They should be thinner and a lighter gray, like here 
![dark_menu](https://user-images.githubusercontent.com/78352816/106771996-dce68600-663f-11eb-918e-6334a7a56240.png)

Secondly, there are still white background sub-menus. 
I'll give a list of what issues I noticed, so far, in the main menu toolbar:
- File > New submenu: double line between Task & Get a New Mail Account...
- File > Get New Messages For has a white background (wbg), but All Accounts has a black icon;
- Go > Folder & all the submenus : wbg
- Message > Move To & Copy To, including all the submenus : wbg
The Move To & Copy To submenus from the message context-menu. 
Then on the Compose Message window, all menus & the context-menu (rclick) have wbg.
Eventually, all the menus from the Address book have a wbg.

**Comment by conema** [comment] 2021-02-04 16:47
> File > New submenu: double line between Task & Get a New Mail Account

![immagine](https://user-images.githubusercontent.com/12801153/106925668-93b23700-6710-11eb-9b24-4c566a36e4c3.png)

I have "folders" and "saved search" between "task" (attività) and "get a new mail account" (crea un nuovo indirizzo email), do you have them? If not, the double line is a Thunderbird bug

**Comment by conema** [comment] 2021-02-04 22:04
The other things that you noted should be fixed here:
[monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5928797/monterail-fulldark.zip)

Thank you for your testing!

**Comment by Gorobei** [comment] 2021-02-05 14:41
You are almost ready. From what I checked, so far, the only wbg I found were in the compose window: paragraph & font lists from the formatting toolbar & the priority pull-down menu
![Para](https://user-images.githubusercontent.com/78352816/107047686-62953d80-67c8-11eb-84dd-2a6f3069fa44.png) ![FontList](https://user-images.githubusercontent.com/78352816/107047693-64f79780-67c8-11eb-8350-fc35c7a15085.png) ![Priority](https://user-images.githubusercontent.com/78352816/107047703-6759f180-67c8-11eb-815c-8192196d4510.png)

**Comment by Gorobei** [comment] 2021-02-05 15:47
> > File > New submenu: double line between Task & Get a New Mail Account
> 
> ![immagine](https://user-images.githubusercontent.com/12801153/106925668-93b23700-6710-11eb-9b24-4c566a36e4c3.png)
> 
> I have "folders" and "saved search" between "task" (attività) and "get a new mail account" (crea un nuovo indirizzo email), do you have them? If not, the double line is a Thunderbird bug

Btw, strange but, no idea why, I still have 2 consecutive horizontal lines with no "Folders" and "Saved search" in between.

**Comment by Gorobei** [comment] 2021-02-05 15:52
> Btw, strange but, no idea why, I still have 2 consecutive horizontal lines with no "Folders" and "Saved search" in between.
Ok, problem solved. If you are on a top level category (smart folder) like Inbox, Sent, Trash ..., you'll see the 2 hlines with nothing between them. If you go a subfolder you will have "Folders" and "Saved search". ;-)

**Comment by conema** [comment] 2021-02-05 17:25
> You are almost ready. From what I checked, so far, the only wbg I found were in the compose window: paragraph & font lists from the formatting toolbar & the priority pull-down menu

That's should do it:
[monterail-fulldark.zip](https://github.com/conema/monterail-fulldark/files/5934187/monterail-fulldark.zip)

**Comment by conema** [comment] 2021-02-10 09:57
I'm closing the issue, if you notice other things, you know where to find me

**Closed by conema** 2021-02-10 09:57 UTC
