### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BetterB0y** [conema/monterail-fulldark#52] opened 2020-10-23 12:24 UTC
Can someone tell me how to change only icons in thunderbird?
Sorry, i didn't know where to write this question

**Comment by conema** [comment] 2020-10-23 13:24
Do you want to use only the icons of this theme without the other enhancements?

**Comment by BetterB0y** [comment] 2020-10-23 13:25
Yeah

**Comment by conema** [comment] 2020-10-23 13:45
This is not really immediate, your best bet is to edit the variables in [root.css](https://github.com/conema/monterail-fulldark/blob/93e88c4b1e311897dee21250df1007d6b64b3824/content/skin/root.css#L11-L50) with the TB default colors.  Alternatively, give a try to [Monterail Dark](https://github.com/conema/monterail-dark), it uses the same icons of this theme, but it's similar to the default TB. If you don't like some particular little aspect of one of the two themes (e.g. you want to change the height of the messages or you want to change the color of the header), let me know and I'll try to help you. 

I'll close this issue, since it isn't a problem of the theme, but feel free to continue the discussion here (you can send new messages also if the issue is closed).

**Closed by conema** 2020-10-23 13:45 UTC
