### ISSUE TITLE
Change icon colour in v 78

### ISSUE THREAD

**Issue by meetdilip** [conema/monterail-fulldark#50] opened 2020-09-14 10:21 UTC
Hi, I tried to do a couple of colour changes in Thunderbird 78.2.2. Most of it was ok. But the icons are still white. I am not sure how to change them to black. It would be nice if you can help me with this. Thanks.

![Thunderbird 78 light](https://user-images.githubusercontent.com/6965443/93074437-fb081580-f6a1-11ea-9bda-81c37b382bbb.png)

**Comment by meetdilip** [comment] 2020-09-14 11:38
Managed to do this by altering icons > CSS  > folder.css

**Comment by meetdilip** [comment] 2020-09-14 11:40
But no luck in the compose email window. Looks like we have to do a lot of trial and error.

**Comment by conema** [comment] 2020-09-14 16:03
Try to look at content/skin/icons/css/compose.css, they should be here. 

PS: I'm closing this issue, since it isn't a bug, but feel free to continue the discussion here, even if the issue is closed

**Closed by conema** 2020-09-14 16:04 UTC

**Comment by meetdilip** [comment] 2020-09-14 22:24
Thanks. I need to ask a doubt. I unzipped the monterail-dark.zip you gave me. I made changes and the zipped it back. But v 78 says it is not a valid add on. All I did was uncompress and then compress again. Any tips will be great.

**Comment by meetdilip** [comment] 2020-09-15 00:37
I got almost all of them fixed. But the text in the sidebar in the address book is eluding me. So does the columns and rows in the calendar. If possible, tell me where to look 

![address book](https://user-images.githubusercontent.com/6965443/93151467-a4d6b900-f719-11ea-8c86-0bc74fd89247.png)


![calender Lightning](https://user-images.githubusercontent.com/6965443/93151468-a607e600-f719-11ea-87da-bfe678bfc90a.png)

**Comment by conema** [comment] 2020-09-15 08:53
> Thanks. I need to ask a doubt. I unzipped the monterail-dark.zip you gave me. I made changes and the zipped it back. But v 78 says it is not a valid add on. All I did was uncompress and then compress again. Any tips will be great.

The files should be in the root of the archive (when you open the archive, you should have manifest.json (and the other files), not a folder, that has these files into). Try also to create an uncompressed zip archive.

> I got almost all of them fixed. But the text in the sidebar in the address book is eluding me. So does the columns and rows in the calendar. If possible, tell me where to look

chrome://monterailoverlay/content/skin/win/skin/addressbook.css
chrome://monterailoverlay/content/skin/messenger.css near row 409
In general search for "treechildren"
